"""Generate a double-clickable macOS app bundle for we.ather.

Writes ~/Applications/we.ather.app: a thin launcher with this repo's path
baked in, output logged to data/weather.log (the terminal messages — sync
failures, new-folder notices — still need somewhere readable:
`tail -f data/weather.log`).

Usage: python -m presence.render.make_app
Rerun after moving the repo. Drag the app to the Dock; right-click →
Options → Open at Login if you want it always-on.
"""

from __future__ import annotations

import sys
from pathlib import Path

from presence.pipeline.config import REPO_ROOT

INFO_PLIST = """<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
 "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>we.ather</string>
  <key>CFBundleDisplayName</key><string>we.ather</string>
  <key>CFBundleExecutable</key><string>weather</string>
  <key>CFBundleIdentifier</key><string>net.weather.presence</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleShortVersionString</key><string>0.1</string>
  <key>LSMinimumSystemVersion</key><string>12.0</string>
</dict>
</plist>
"""

LAUNCHER = """#!/bin/bash
# we.ather launcher — generated by presence.render.make_app
cd "{repo}" || exit 1
echo "--- we.ather launch $(date) ---" >> data/weather.log
exec .venv/bin/python -m presence.render.app >> data/weather.log 2>&1
"""


def baked_repo(bundle: Path) -> Path | None:
    """The install folder an existing bundle's launcher points at."""
    launcher = bundle / "Contents" / "MacOS" / "weather"
    if not launcher.is_file():
        return None
    for line in launcher.read_text().splitlines():
        if line.startswith('cd "'):
            return Path(line.split('"')[1])
    return None


def make_app(target_dir: Path, repo: Path = REPO_ROOT) -> Path:
    bundle = target_dir / "we.ather.app"
    previous = baked_repo(bundle)
    if previous is not None and previous != repo:
        # One Dock app, one baked path: rebuilding from a second install
        # (e.g. a test folder) silently repoints the icon — say so.
        print(f"NOTE: replacing the Dock app that pointed at {previous}")
        print("      (rerun make_app from that folder to point it back)")
    macos = bundle / "Contents" / "MacOS"
    macos.mkdir(parents=True, exist_ok=True)
    (bundle / "Contents" / "Info.plist").write_text(INFO_PLIST)
    launcher = macos / "weather"
    launcher.write_text(LAUNCHER.format(repo=repo))
    launcher.chmod(0o755)
    return bundle


def main() -> None:
    target = Path(sys.argv[1]) if len(sys.argv) > 1 else Path.home() / "Applications"
    target.mkdir(parents=True, exist_ok=True)
    bundle = make_app(target)
    print(f"created {bundle}")
    print("double-click it in Finder to open (built locally, so macOS")
    print("doesn't block it), then drag it to the Dock.")
    print(f"app output logs to: {REPO_ROOT / 'data' / 'weather.log'}")


if __name__ == "__main__":
    main()
